//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTask
    {
        public int SubTaskCode { get; set; }
        public string SubTaskName { get; set; }
        public int TaskCode { get; set; }
        public System.DateTime SubTaskDate { get; set; }
        public System.TimeSpan BeginingTime { get; set; }
        public double duration { get; set; }
        public int status { get; set; }
        public string details { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
