//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.SubTasks = new HashSet<SubTask>();
        }
    
        public int TaskCode { get; set; }
        public string TaskName { get; set; }
        public int EventCode { get; set; }
        public int EventTypeCode { get; set; }
        public System.DateTime DeadLine { get; set; }
        public int ProfessionalCode { get; set; }
        public int TaskStatus { get; set; }
        public System.DateTime BeginingTime { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Professional Professional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTask> SubTasks { get; set; }
    }
}
